tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT=on-partial

    before: #Installation of AWS CLI
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT #cds back to workspace after creating the CLI through the use of env variable\

      # Setting the env variables like this or through credential files
      # gp env AWS_ACCESS_KEY_ID=...
      # gp env AWS_SECRET_ACCESS_KEY=...
      # gp env AWS_DEFAULT_REGION=...
      # exported aws cli auto-prompt(look up)

 