tasks:
  - name: aws-cli
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    before: #Installation of AWS CLI
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

# # List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# # Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
